name       : uncrustify
version    : 0.75.1
release    : 7
source     :
    - https://github.com/uncrustify/uncrustify/archive/uncrustify-0.75.1.tar.gz : fd14acc0a31ed88b33137bdc26d32964327488c835f885696473ef07caf2e182
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala
description: |
    Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala.
    The goals of this project are simple: Create a highly configurable, easily modifiable source code beautifier.
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
