name       : uncrustify
version    : 0.72.0
release    : 6
source     :
    - https://github.com/uncrustify/uncrustify/archive/uncrustify-0.72.0.tar.gz : d6fff70bc7823fac4c77013055333b79a4839909094e8eee8a14ee8f1777374e
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala
description: |
    Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala.
    The goals of this project are simple: Create a highly configurable, easily modifiable source code beautifier.
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
