name       : uncrustify
version    : 0.65
release    : 2
source     :
    - https://github.com/uncrustify/uncrustify/archive/uncrustify-0.65.tar.gz : 45e954cd207ee4f6531d72ece27554ef4e0e9f64c912b523bc80ad6a36404110
license    : GPL-2.0
component  : programming.tools
summary    : Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala
description: |
    Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala.
    The goals of this project are simple: Create a highly configurable, easily modifiable source code beautifier.
setup      : |
    mkdir build
    cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
